### PR TITLE
I wanted this for my use case, thought it may be useful to others.

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
If you don't want it, or wanna do it differently, no worries.

### CODE REVIEW

**Comment by tj** [comment]
we have `.closable()` which emits an event

**Comment by HenrikJoreteg** [comment]
Ok, so how would you suggest handling the case where a user is trying
to take action on a notification, not close it?

For example when you click a normal desktop Growl notification it
usually takes you to that app and whatever is relevant to the
notification.

On Feb 6, 2012, at 8:23, TJ Holowaychuk
reply@reply.github.com
wrote:

**Comment by tj** [comment]
ah I see, I've never clicked a growl notification before. I guess we could just have `.on('click'` though even from a UX point of view that's not obvious IMO, a link in the notification or something would be better

**Comment by HenrikJoreteg** [comment]
Well, I agree from a UX perspective that it may not be obvious, but part of that depends on how the notifications are styled. I've got a web app that use Growl if available (if running as a Fluid app or desktop-wrapped app) and I'm planning on using UI kit notifications as a fallback for that. So for me, it's be great if I could supply similar options.

I agree with what you're saying using the `.on('click')` api. I updated the pull request.

Anyway, I can just do what I've already done, but I think it'd be cool if this behavior (in some form) existed in the lib itself. Cheers!

**Comment by tj** [comment]
cool thanks I'll take the updated version

**Pull request merged**
