### PR TITLE
emit escape and close on escape

### PR DESCRIPTION
**Pull request by pgherveou**
this will also cause the confirmation to fire the callback on escape

### CODE REVIEW

**Comment by tj** [comment]
ohhh you know what, "hide" was the event that i was thinking of when we were discussing, which we already have for this. "close" "escape" would be more explicit than the more generic "hide"

**Comment by tj** [comment]
so i think just "escape"

**Comment by pgherveou** [comment]
as you wish, if we just do escape we will need to add a handler for this event in Confirmation.prototype.render

``` javascript
    this.on('close', function(){
      self.emit('cancel');
      self.callback(false);
    });

    this.on('escape', function(){
      self.emit('cancel');
      self.callback(false);
    });

```

not really dry unless you want to add the ability to call 'on' with multiple event like jquery does

**Comment by tj** [comment]
hmmm yeah that's fine for now I guess, not the end of the world. comma-separated events or arrays would be reasonable too but let's do this first

**Comment by pgherveou** [comment]
I made a bad manip had to create another -> #51

**Pull request closed without merging**
